# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import env_pb2 as env__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PikaEnvStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/pika.env.v1.PikaEnv/Configure',
                request_serializer=env__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=env__pb2.ConfigureReply.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/pika.env.v1.PikaEnv/Reset',
                request_serializer=env__pb2.ResetRequest.SerializeToString,
                response_deserializer=env__pb2.StepReply.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/pika.env.v1.PikaEnv/Step',
                request_serializer=env__pb2.StepRequest.SerializeToString,
                response_deserializer=env__pb2.StepReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/pika.env.v1.PikaEnv/Health',
                request_serializer=env__pb2.HealthRequest.SerializeToString,
                response_deserializer=env__pb2.HealthReply.FromString,
                _registered_method=True)
        self.FetchReplays = channel.unary_unary(
                '/pika.env.v1.PikaEnv/FetchReplays',
                request_serializer=env__pb2.FetchReplaysRequest.SerializeToString,
                response_deserializer=env__pb2.FetchReplaysReply.FromString,
                _registered_method=True)


class PikaEnvServicer:
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """벡터 크기·슬롯 구성·플래그를 정한다. 기존 상태는 버려진다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """전부 처음 상태로. 반환은 Step 과 같은 모양이며 보상·플래그는 0 이다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """버전·관측 레이아웃 해시·누적 처리량. 클라이언트가 붙자마자 대조한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchReplays(self, request, context):
        """기록된 게임(리플레이 v1 바이트)을 꺼내고 서버 큐를 비운다. (Phase 4 FR-6)
        record_replays 가 꺼져 있으면 항상 비어 있다. 어느 게임을 집계에 넣을지는 클라이언트가
        (env_index, game_in_env) 로 고른다 — 서버는 끝난 게임을 전부 쌓는다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PikaEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=env__pb2.ConfigureRequest.FromString,
                    response_serializer=env__pb2.ConfigureReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=env__pb2.ResetRequest.FromString,
                    response_serializer=env__pb2.StepReply.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=env__pb2.StepRequest.FromString,
                    response_serializer=env__pb2.StepReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=env__pb2.HealthRequest.FromString,
                    response_serializer=env__pb2.HealthReply.SerializeToString,
            ),
            'FetchReplays': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchReplays,
                    request_deserializer=env__pb2.FetchReplaysRequest.FromString,
                    response_serializer=env__pb2.FetchReplaysReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pika.env.v1.PikaEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pika.env.v1.PikaEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PikaEnv:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pika.env.v1.PikaEnv/Configure',
            env__pb2.ConfigureRequest.SerializeToString,
            env__pb2.ConfigureReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pika.env.v1.PikaEnv/Reset',
            env__pb2.ResetRequest.SerializeToString,
            env__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pika.env.v1.PikaEnv/Step',
            env__pb2.StepRequest.SerializeToString,
            env__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pika.env.v1.PikaEnv/Health',
            env__pb2.HealthRequest.SerializeToString,
            env__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchReplays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pika.env.v1.PikaEnv/FetchReplays',
            env__pb2.FetchReplaysRequest.SerializeToString,
            env__pb2.FetchReplaysReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
